// Mock data for dashboard UI — replace with real DB calls once Prisma is set up

export const mockUser = {
  id: "user_1",
  name: "John Doe",
  email: "john@example.com",
  image: null,
  isPro: false,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "Snippet",  icon: "Code",       color: "#3b82f6", isSystem: true,  userId: null },
  { id: "type_prompt",  name: "Prompt",   icon: "Sparkles",   color: "#8b5cf6", isSystem: true,  userId: null },
  { id: "type_command", name: "Command",  icon: "Terminal",   color: "#f97316", isSystem: true,  userId: null },
  { id: "type_note",    name: "Note",     icon: "StickyNote", color: "#fde047", isSystem: true,  userId: null },
  { id: "type_file",    name: "File",     icon: "File",       color: "#6b7280", isSystem: true,  userId: null },
  { id: "type_image",   name: "Image",    icon: "Image",      color: "#ec4899", isSystem: true,  userId: null },
  { id: "type_link",    name: "Link",     icon: "Link",       color: "#10b981", isSystem: true,  userId: null },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useAuth Hook",
    contentType: "TEXT" as const,
    content: "Custom authentication hook for React applications.\n\n```ts\nexport function useAuth() {\n  const session = useSession();\n  return { user: session?.user, isLoading: !session };\n}\n```",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "Custom authentication hook for React applications",
    language: "typescript",
    isFavorite: false,
    isPinned: true,
    userId: "user_1",
    itemTypeId: "type_snippet",
    tags: ["react", "auth", "hooks"],
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-01-15"),
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    contentType: "TEXT" as const,
    content: "Fetch wrapper with exponential backoff retry logic.",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "Fetch wrapper with exponential backoff retry logic",
    language: "typescript",
    isFavorite: false,
    isPinned: true,
    userId: "user_1",
    itemTypeId: "type_snippet",
    tags: ["api", "error-handling"],
    createdAt: new Date("2026-01-13"),
    updatedAt: new Date("2026-01-13"),
  },
  {
    id: "item_3",
    title: "Git branch cleanup",
    contentType: "TEXT" as const,
    content: "git branch --merged | grep -v '\\*\\|main\\|develop' | xargs git branch -d",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "Delete all merged local branches",
    language: null,
    isFavorite: true,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_command",
    tags: ["git", "cleanup"],
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-01-10"),
  },
  {
    id: "item_4",
    title: "Code explainer prompt",
    contentType: "TEXT" as const,
    content: "Explain this code step by step as if teaching a junior developer. Highlight any potential issues or improvements.",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "General-purpose code explanation prompt",
    language: null,
    isFavorite: true,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_prompt",
    tags: ["ai", "code-review"],
    createdAt: new Date("2026-01-08"),
    updatedAt: new Date("2026-01-08"),
  },
  {
    id: "item_5",
    title: "Next.js App Router cheatsheet",
    contentType: "TEXT" as const,
    content: "Quick reference for Next.js 15 App Router patterns.",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "Quick reference for App Router conventions",
    language: null,
    isFavorite: false,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_note",
    tags: ["nextjs", "reference"],
    createdAt: new Date("2026-01-05"),
    updatedAt: new Date("2026-01-05"),
  },
  {
    id: "item_6",
    title: "Prisma query examples",
    contentType: "TEXT" as const,
    content: "```ts\nawait prisma.user.findMany({ where: { isPro: true }, include: { items: true } });\n```",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "Common Prisma ORM query patterns",
    language: "typescript",
    isFavorite: false,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_snippet",
    tags: ["prisma", "database"],
    createdAt: new Date("2026-01-03"),
    updatedAt: new Date("2026-01-03"),
  },
  {
    id: "item_7",
    title: "Docker compose for Postgres",
    contentType: "TEXT" as const,
    content: "version: '3.8'\nservices:\n  db:\n    image: postgres:16\n    ports:\n      - '5432:5432'",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "Quick local Postgres setup with Docker Compose",
    language: "yaml",
    isFavorite: false,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_command",
    tags: ["docker", "postgres"],
    createdAt: new Date("2026-01-02"),
    updatedAt: new Date("2026-01-02"),
  },
  {
    id: "item_8",
    title: "Tailwind responsive breakpoints",
    contentType: "TEXT" as const,
    content: "sm: 640px, md: 768px, lg: 1024px, xl: 1280px, 2xl: 1536px",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "Default Tailwind CSS breakpoint reference",
    language: null,
    isFavorite: true,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_note",
    tags: ["tailwind", "css", "reference"],
    createdAt: new Date("2025-12-28"),
    updatedAt: new Date("2025-12-28"),
  },
  {
    id: "item_9",
    title: "System prompt template",
    contentType: "TEXT" as const,
    content: "You are a helpful assistant specialized in {domain}. Follow these rules:\n1. Be concise\n2. Use examples\n3. Cite sources",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "Reusable system prompt template for AI assistants",
    language: null,
    isFavorite: false,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_prompt",
    tags: ["ai", "template"],
    createdAt: new Date("2025-12-25"),
    updatedAt: new Date("2025-12-25"),
  },
  {
    id: "item_10",
    title: "MDX Blog Setup",
    contentType: "URL" as const,
    content: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: "https://nextjs.org/docs/app/building-your-application/configuring/mdx",
    description: "Official Next.js MDX integration guide",
    language: null,
    isFavorite: false,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_link",
    tags: ["nextjs", "mdx", "blog"],
    createdAt: new Date("2025-12-20"),
    updatedAt: new Date("2025-12-20"),
  },
  {
    id: "item_11",
    title: "npm audit fix script",
    contentType: "TEXT" as const,
    content: "npm audit fix --force && npm dedupe && npm prune",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "Quick command to fix npm vulnerabilities",
    language: null,
    isFavorite: false,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_command",
    tags: ["npm", "security"],
    createdAt: new Date("2025-12-18"),
    updatedAt: new Date("2025-12-18"),
  },
  {
    id: "item_12",
    title: "Zod validation patterns",
    contentType: "TEXT" as const,
    content: "```ts\nconst schema = z.object({\n  email: z.string().email(),\n  age: z.number().min(18),\n});\n```",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "Common Zod schema validation patterns for forms",
    language: "typescript",
    isFavorite: false,
    isPinned: false,
    userId: "user_1",
    itemTypeId: "type_snippet",
    tags: ["zod", "validation", "typescript"],
    createdAt: new Date("2025-12-15"),
    updatedAt: new Date("2025-12-15"),
  },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    defaultTypeId: "type_snippet",
    userId: "user_1",
    itemCount: 12,
    dominantTypeColor: "#3b82f6",
    itemTypeIcons: ["Code", "Sparkles", "Link"],
    createdAt: new Date("2025-12-01"),
    updatedAt: new Date("2026-01-15"),
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    defaultTypeId: "type_snippet",
    userId: "user_1",
    itemCount: 8,
    dominantTypeColor: "#3b82f6",
    itemTypeIcons: ["Code", "Terminal"],
    createdAt: new Date("2025-12-05"),
    updatedAt: new Date("2026-01-10"),
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    defaultTypeId: "type_file",
    userId: "user_1",
    itemCount: 5,
    dominantTypeColor: "#6b7280",
    itemTypeIcons: ["File", "Image"],
    createdAt: new Date("2025-12-10"),
    updatedAt: new Date("2026-01-12"),
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    defaultTypeId: "type_note",
    userId: "user_1",
    itemCount: 24,
    dominantTypeColor: "#fde047",
    itemTypeIcons: ["StickyNote", "Code", "Link", "Sparkles"],
    createdAt: new Date("2025-11-20"),
    updatedAt: new Date("2026-01-08"),
  },
  {
    id: "col_5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    defaultTypeId: "type_command",
    userId: "user_1",
    itemCount: 15,
    dominantTypeColor: "#f97316",
    itemTypeIcons: ["Terminal", "Code"],
    createdAt: new Date("2025-11-25"),
    updatedAt: new Date("2026-01-06"),
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    defaultTypeId: "type_prompt",
    userId: "user_1",
    itemCount: 18,
    dominantTypeColor: "#8b5cf6",
    itemTypeIcons: ["Sparkles", "Code"],
    createdAt: new Date("2025-12-15"),
    updatedAt: new Date("2026-01-04"),
  },
];

// Item counts per type — used by the sidebar
export const mockTypeCounts: Record<string, number> = {
  type_snippet: 24,
  type_prompt:  18,
  type_command: 15,
  type_note:    12,
  type_file:     5,
  type_image:    3,
  type_link:     8,
};
